### ISSUE TITLE
Edit Global Mazda MX-5 Cup shift point to 7200 rpm

### ISSUE THREAD

**Issue by m-jepson** [samkatakouzinosracing/nspace.hu-soundshift#91]
It's set at 6400 rpm now, which is hit almost immediately after changing up a gear. I have set it at 7200 rpm now, which is also the exact moment the red light comes up in game and gives you just enough time to change gears before hitting the limiter. In the MX-5, afaik, it's important to stay in a gear as long as possible to get the best acceleration.

So, can you please update it to 7200 rpm?

**Comment by m-jepson** [comment]
To make it easier, I've created a pull request:
https://github.com/samkatakouzinosracing/nspace.hu-soundshift/pull/92

**Comment by samkatakouzinosracing** [comment]
@m-jepson you're right. RPM at 6400 is way too low a shift point for the mx52016. 

I tested the Global Mazda MX-5 at Talladega and apart for 1st gear, 7300 rpm seems a better shift point than 7200 rpm. 
But I fear that 7300 rpm as the new default may consistently catch out few drivers for 1st gear.

I will go ahead with 7200 rpm for simple ticked settings. 
Personally after 1st gear I would unselect simple and bump 2nd gear up 100 so that the rest of the gears signal at 7300. 
As you stated it's important to stay in gear as long as possible. 

Note to self: regularly clear out my own customisations to take on a fresh vehicle.ini update.
